CREATE DATABASE IF NOT EXISTS vehicle_db;
CREATE DATABASE IF NOT EXISTS booking_db;
CREATE DATABASE IF NOT EXISTS trip_db;
CREATE DATABASE IF NOT EXISTS record_db;
CREATE DATABASE IF NOT EXISTS maintenance_db;
CREATE DATABASE IF NOT EXISTS pricing_db;
CREATE DATABASE IF NOT EXISTS payment_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS search_db;
CREATE DATABASE IF NOT EXISTS process_booking_db;
CREATE DATABASE IF NOT EXISTS external_damage_db;
CREATE DATABASE IF NOT EXISTS start_trip_db;
CREATE DATABASE IF NOT EXISTS internal_damage_db;
CREATE DATABASE IF NOT EXISTS end_trip_db;
CREATE DATABASE IF NOT EXISTS handle_damage_db;
CREATE DATABASE IF NOT EXISTS renewal_reconciliation_db;

