_format_version: "3.0"

services:
  - name: web
    url: http://web
    routes:
      - name: web-root
        paths: ["/"]
        strip_path: false
  - name: search-available-vehicles-service
    url: http://search-available-vehicles-service:8000
    routes:
      - name: search-available-routes
        paths: ["/search-vehicles"]
        strip_path: false
  - name: process-booking-service
    url: http://process-booking-service:8000
    routes:
      - name: process-booking-routes
        paths: ["/process-booking"]
        strip_path: false
  - name: trip-experience-service
    url: http://trip-experience-service:8000
    routes:
      - name: trip-experience-routes
        paths: ["/trip-experience"]
        strip_path: false
  - name: ops-console-service
    url: http://ops-console-service:8000
    routes:
      - name: ops-console-routes
        paths: ["/ops-console"]
        strip_path: false
