_format_version: "3.0"

services:
  - name: web
    url: http://web
    routes:
      - name: web-root
        paths: ["/"]
        strip_path: false
  - name: search-available-vehicles-service
    url: http://search-available-vehicles-service:8000
    routes:
      - name: search-available-routes
        paths: ["/search-vehicles"]
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 10
          policy: local
          limit_by: ip
  - name: process-booking-service
    url: http://process-booking-service:8000
    routes:
      - name: process-booking-routes
        paths: ["/process-booking"]
        strip_path: false
  - name: rental-execution-service
    url: http://rental-execution-service:8000
    routes:
      - name: rental-execution-routes
        paths: ["/rental-execution"]
        strip_path: false
  - name: ops-console-service
    url: http://ops-console-service:8000
    routes:
      - name: ops-console-routes
        paths: ["/ops-console"]
        strip_path: false
    plugins:
      - name: key-auth
        config:
          key_names:
            - X-Mechanic-Key
          hide_credentials: true
          key_in_header: true
          key_in_query: false
          key_in_body: false

consumers:
  - username: mechanic-dashboard
    keyauth_credentials:
      - key: ops-demo-key-fleetshare